################################# Default configuration ###################
baseURL = "http://localhost:1313/"
title = "juuri.ai"
#theme = ""
# default language
defaultContentLanguage = "fi"
# post pagination
[pagination]
pagerSize = 6
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language - disable French to keep only Finnish and English
disableLanguages = ["fr"]

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
# link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
#link = "https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
link = "https://fonts.googleapis.com/css2?family=Open+Sans:400,700&display=swap"
# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "Services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "Team"
url = "#team"
weight = 4

[[Languages.en.menu.main]]
name = "Pricing"
url = "#pricing"
weight = 5

[[Languages.en.menu.main]]
name = "Blog"
url = "#blog"
weight = 6

[[Languages.en.menu.main]]
name = "Contact"
url = "#contact"
weight = 7

################### Finnish Navigation ########################
[[Languages.fi.menu.main]]
name = "Tietoa"
url = "#about"
weight = 1

[[Languages.fi.menu.main]]
name = "Palvelut"
url = "#services"
weight = 2

[[Languages.fi.menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 3

[[Languages.fi.menu.main]]
name = "Tiimi"
url = "#team"
weight = 4

[[Languages.fi.menu.main]]
name = "Hinnat"
url = "#pricing"
weight = 5

[[Languages.fi.menu.main]]
name = "Blogi"
url = "#blog"
weight = 6

[[Languages.fi.menu.main]]
name = "Yhteystiedot"
url = "#contact"
weight = 7

############################# Default Parameters ##########################
[params]
logo = "images/juuri-ai-logo.png"
# Meta data
description = "juuri.ai - Responsive Multilingual Hugo Website"
author = "juuri.ai Team"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/juuri-ai-logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "60.976896"
map_longitude = "24.467889"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
enable = true
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
enable = true
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
enable = false
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
enable = true
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
enable = false
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
enable = false
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"

################################ English Language ########################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2025 juuri.ai. All rights reserved."

################################ Finnish Language ########################
[Languages.fi]
languageName = "Suomi"
languageCode = "fi-fi"
contentDir = "content/fi"
weight = 2
home = "Koti"
copyright = "Copyright &copy; 2025 juuri.ai. Kaikki oikeudet pidätetään."
