backend:
  name: github
  repo: polari1/git-sveltia
  branch: main
  client_id: Ov23liyDhZ6fiTvHYUbV

media_folder: "static/images"
public_folder: "/images"

collections:
  # Test with just ONE file to see if it works
  - name: "test_single"
    label: "Test Single File"
    files:
      - label: "Test Post"
        name: "test_post"
        file: "content/english/blog/test-sveltia.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Date", name: "date", widget: "datetime"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}